apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: emailreplyio-sticky-session
  namespace: emailreplyio 
  labels:
    app: emailreplyio
spec:
  weighted:
    sticky:
      cookie:
        name: emailreplyio-session-lv1
    services:
      - name: svc-emailreplyio
        port: 80
        weight: 100
        sticky:
          cookie:
            httpOnly: false
            name: emailreplyio-session-lv2
            secure: true
            samSite: strict
