apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emailreplyio-ssl-cert
  namespace: emailreplyio
  labels:
    app: emailreplyio
spec:
  secretName: emailreplyio-ssl-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'emailreply.io'