{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "dockerhub-credentials",
    "namespace": "emailreply",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "dockerhub-credentials",
        "namespace": "emailreply",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgCdB08bxcFMLDPpNsZf+GOvvKLNbEE1DB37ohUGR+tVQMfR5hbBKFR2F2eXNLLLEmx9ZNukmKz9Xg2l3TCfghw7QTyZokTRLuBOFNTQcgZ+x9xzQL9FjAsMFR/VWemAlf5un94fMinhTryE4lEScqM//O81ycZfkLGFyYbi3x7sf94KVPQANRUFWHaJd+2Swhev4EQKe8p3Vb4HEru+mHuHSJO8jLufganG0QY4/mYEVCyyLeoxkNk3iAN60TOsiL+Lr3l013XoT2HUOkZFTupCjg6jr1hsfTephbj9cP/+WoNJP+ofYhE/aj3qCpy3edQtQ5czj7mxWe/BKmfMf50NlZxFR8GfTstz2hsPtFmQjIu+Z5lkRQSavQ/AmO2mih4/BoJE1Zs9Ip+hnvS5r1o8M28d4VEGRBrMn93PDdKYX5k4ZWHRubVVjIFeZzfxp7wP7MQD6Ec++VW5ShDWF2w7B6/OZO9kpRZEy9vBYSxQjn6nAY3L08NrjYjsoGqhVUh6vAsyGmGGBWqw1rK7gCJSsattoRU8p8mNhVuQ7Vq5xsPd0gFerdjBF8+jbI2OHMi/6qQhag6Z+xp3+5j4l0MY6xCSiZyTqwNTaVmBfWckzBP6BdbsLafioF5Q1eP/MxE9A+KP5TdqhJrKUVI441E7vi6Jm9uQv0JMikKdN/k/s08uG4X5SQx3HqgC/lXt50evJ5+bqGvcxcPn+EshCoReU+GWHxfDs+ocfJLnYqhWhQ5p5KoM3A8eUCtLn0pAu2WROO5yd5KW3HM2EO2b5JphqGNbhrY4MrlGQROw61x+W7afEKatl3MzBkHHoKQKdFiH71nvYmNRtY5a3365Z/DdoCa0pNyixE3+hExEvCnBt9rUW00GNx7ruN8/aVzH3iQfjeQUj0ucTNFpKhxGx5V2YtcdNYNGKCV6Wnj0A2m01fPu+qaAKw7UVv43KyPYMt/UthW5YH8o3NYYB7wR7B/KrCiRo0LIonNxBHm4NUh5Ekw="
    }
  }
}
