{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "dockerhub-credentials",
    "namespace": "emailreplyio",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "dockerhub-credentials",
        "namespace": "emailreplyio",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgA8AwuASw7oB+vqM5OOuSwR/Ykn5YPFQMzCKrLCtFY1FZjpoOEbSuq6gk4H+EWuthiHma8QsT8YUuOogRsmoEyJGfIc45KeNbzoT3oz1bzPk5c1FiwqltI/t4/rQ5LicJ0udoNdiRzjKhHouV3EznaH4MZ69sMMirDbeflOklZMCW831nL4NoLZA/93ig0eyvRv1OcO3wuBuxWvX9Fq8iib+QR5fFHS5aAw7txH9PvUfIOQZc/TwzN4FzIls0F4kjIhDE2kATnFU6zqInJnD0c4C7bCWRLNb0RAoSy7k6ybbo1WwRrpdbhI6kOpVkpJiGYFZVpguFMpIu7ecZrAYL1+kJ14hSB96cvQ+G85jv2APIZGEKcTuf54VJfbVh7DzieEFUhFnUsoZsa/omvxG7ZTpqisbsPmaB9r++wlrO3ScOlrV6wJtcqw9PUbmxuvKEHePS/0hVdCXeJ+JWKAOVkLVHMm3WFaT8xMqV32pIv4+Y1JUslnNa5n3yqdW5r9c5STcei8l1ujHiOjVMGR1Bbag0kyDpFbqMisH87PiWVZ4J3ydR0emhbuHsme0zljqLN9wkPiiyCpVKZNOqvLftPRMvVzFjpWVf7jP5A8rtI7hWLHI7jIWWubhfC4qhLxFSGSct5iFB2wopgpW4UHv5OCOZwaJo6MvUJ310jqUvlpOskRgzc3KFQICC6VhWwftmoyTjrZAWjyc5qrele59dewhvsEz0gEVi0OUglNN/v6bYKob5tOrnewaIMgcg478JdAsacSPCr4NHGigiGLlWzsWIs3SW0H092imQAlLh+eAktOIN8eB3uo+SLRwRdRtuDL6PMUOWHO7uXp1qkx1siZoX98EVJgS5zVQpWpz3k2DshJsJDuVZEts8VXScu8JVpFAdwzk3CZleEXiov3OR2zfVxNAtzQ2+dMM4VBoZ03yveB3WsCRcDCgFL7vSL9kIOD9+YNpaY/P7oMeTzj/O/MElKEAFBJeW6AaGpFMLK2Zkw="
    }
  }
}
