{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "OPENAI_API_KEY",
    "namespace": "emailreplyio",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "OPENAI_API_KEY",
        "namespace": "emailreplyio",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "openai-api-key": "AgCg55mcKwv+bpjhjeq7OcisA6uMMj0RLMJqbOhtT2nG6DS9F8P9ZGb7WPr2gFv+glV3wr2YXtO4bqmi2CSGJF8t9H1Q6W0TNaxJI1coWnmDgjW+CutVZ/fcLfQLtkJDHQk4nUY3e0jpcC4AIG+SEy+N7SgXkDXPVr2C5vhmTQd05d2xXD8TYdaHchR+4kMNLjy8aB9nGcKEnV6tKWWbL3XUP9NNvs/vVOW5Mc/6qIFSgsic/vtPt0kujJJlN0Vc1Oreya9hzJpBYyB7GUcZxAkZDrs5KdAsSJ2zBL58vKzwHk2JrTi2wzBIqgQoEyvaD72aBhUFmYSWJ+kedxF1MC2n9u4QFDQuoL8VGlX9YaFrCciHucwycKuMq25uoAvSscXYqqywX+EQ4/EqGIKazPjx2R86DPYhM22DNFj8uylunvQguXENwfxo5tVwlGy5KndFhTjEP2zvlA2HtvmrSjRyWPp3bl4c0UVqZRI3PHpjqDLZFDy3G0xNy3o3kwTJ3qiSUsgH3jQSIF7RBq36KSW4vJmGIOqeyWZj2/jBe9S0VZl2ZsQuB4JM5myuO3Xw+1k5wYT7m1ISlscd7H2r/x6mttFhgD5xaWOSwvB/Ld/wNfc/7L+j97stvqFJe8lQg9lH2lLmIeLX4yzuM6FgbSsG5l4j4VNH3fJ7iJchxf03MHMkJplAqp22gHy9r3/6VeKHUlTDALl29TPRhwMsxyG7A2r+cKPyj9vj2+TyLvQXm566necYgQfRSw+zGpeGI8Fim10="
    }
  }
}
