name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      
      run: |
        cd ./EmailReplyIo
        docker build -t choejsager/emailreply_io:$GITHUB_RUN_NUMBER .
        docker push choejsager/emailreply_io:$GITHUB_RUN_NUMBER
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: production
        persist-credentials: false

    - name: Update manifest
      run: |
        echo "Updating image from:"
        cat ./manifests/deployments/deployment.yaml | grep -i "image:"
        sed -i "s\choejsager/emailreply_io:.*\choejsager/emailreply_io:${GITHUB_RUN_NUMBER}\g" ./manifests/deployments/deployment.yaml
        echo "Updated image to:"
        cat ./manifests/deployments/deployment.yaml | grep -i "image:"
    - name: Commit files
      run: |
        git config --local user.email "christian@hoejsager.com"
        git config --local user.name "hoejsagerc"
        git commit -a -m "Creating release from: $GITHUB_RUN_NUMBER"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: production
